### ISSUE TITLE
`go run  main.go --help` print help and continue running the app

### ISSUE THREAD

**Issue by xmlking** [micro/go-micro#1154]
**Describe the bug**

1. What are you trying to do?
> run my apps with `--help`  arg
2. What did you expect to happen?
> should print help and exit.
3. What happens instead?
> print help and continue running app

**How to reproduce the bug:**

clone https://github.com/xmlking/micro-starter-kit

run
```bash
go run srv/greeter/main.go --help
```

**Environment:**
Go Version: please paste `go version` output here
```
go version go1.13.6 darwin/amd64
```

> go run srv/greeter/main.go --help                       

```
                      
NAME:
   greetersrv - a go-micro service

USAGE:
   main [global options] command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --client value                  Client for go-micro; rpc [$MICRO_CLIENT]
   --client_request_timeout value  Sets the client request timeout. e.g 500ms, 5s, 1m. Default: 5s [$MICRO_CLIENT_REQUEST_TIMEOUT]
   --client_retries value          Sets the client retries. Default: 1 (default: 1) [$MICRO_CLIENT_RETRIES]
   --client_pool_size value        Sets the client connection pool size. Default: 1 (default: 0) [$MICRO_CLIENT_POOL_SIZE]
   --client_pool_ttl value         Sets the client connection pool ttl. e.g 500ms, 5s, 1m. Default: 1m [$MICRO_CLIENT_POOL_TTL]
   --register_ttl value            Register TTL in seconds (default: 60) [$MICRO_REGISTER_TTL]
   --register_interval value       Register interval in seconds (default: 30) [$MICRO_REGISTER_INTERVAL]
   --server value                  Server for go-micro; rpc [$MICRO_SERVER]
   --server_name value             Name of the server. go.micro.srv.example [$MICRO_SERVER_NAME]
   --server_version value          Version of the server. 1.1.0 [$MICRO_SERVER_VERSION]
   --server_id value               Id of the server. Auto-generated if not specified [$MICRO_SERVER_ID]
   --server_address value          Bind address for the server. 127.0.0.1:8080 [$MICRO_SERVER_ADDRESS]
   --server_advertise value        Used instead of the server_address when registering with discovery. 127.0.0.1:8080 [$MICRO_SERVER_ADVERTISE]
   --server_metadata value         A list of key-value pairs defining metadata. version=1.0.0 [$MICRO_SERVER_METADATA]
   --broker value                  Broker for pub/sub. http, nats, rabbitmq [$MICRO_BROKER]
   --broker_address value          Comma-separated list of broker addresses [$MICRO_BROKER_ADDRESS]
   --profile value                 Debug profiler for cpu and memory stats [$MICRO_DEBUG_PROFILE]
   --registry value                Registry for discovery. etcd, mdns [$MICRO_REGISTRY]
   --registry_address value        Comma-separated list of registry addresses [$MICRO_REGISTRY_ADDRESS]
   --runtime value                 Runtime for building and running services e.g local, kubernetes (default: "local") [$MICRO_RUNTIME]
   --selector value                Selector used to pick nodes for querying [$MICRO_SELECTOR]
   --store value                   Store used for key-value storage [$MICRO_STORE]
   --store_address value           Comma-separated list of store addresses [$MICRO_STORE_ADDRESS]
   --store_namespace value         Namespace for store data [$MICRO_STORE_NAMESPACE]
   --transport value               Transport mechanism used; http [$MICRO_TRANSPORT]
   --transport_address value       Comma-separated list of transport addresses [$MICRO_TRANSPORT_ADDRESS]
   --tracer value                  Tracer for distributed tracing, e.g. memory, jaeger (default: "memory") [$MICRO_TRACER]
   --tracer_address value          Comma-separated list of tracer addresses [$MICRO_TRACER_ADDRESS]
   --configDir value, -d value     Path to the config directory. Defaults to 'config' (default: "/config") [$CONFIG_DIR]
   --configFile value, -f value    Config file in configDir. Defaults to 'config.yaml' (default: "config.yaml") [$CONFIG_FILE]
   --help, -h                      show help (default: false)
INFO[0000] 
version     : untouched
build date  : 
go version  : go1.13.6
go compiler : gc
platform    : darwin/amd64
git commit  : 
git branch  : 
git state   : 
git summary :  
2020-02-02 17:41:07 Starting [service] greetersrv
2020-02-02 17:41:07 Server [grpc] Listening on [::]:54557
2020-02-02 17:41:07 Registry [mdns] Registering node: greetersrv-d945bb7b-88de-464a-bf1b-5feb703eb7a7
^C2020-02-02 17:42:50 Deregistering node: greetersrv-d945bb7b-88de-464a-bf1b-5feb703eb7a7
```

**Comment by nsemikov** [comment]
+1

**Comment by vtolstov** [comment]
this is buf in github.com/micro/cli (urfave/cli fork) we need to understand how to proper needs to handle such case. I'm check other software that uses urfave/cli and nothing unusual

**Comment by asim** [comment]
Its because urfave/cli no longer exits after help flags are used. We need to explicitly check for them and exit. Likely in config/cmd. May even need to override the help command.

**Comment by vtolstov** [comment]
fixed in master, try to update go get github.com/micro/cli/v2@master

**Comment by nsemikov** [comment]
> fixed in master, try to update go get github.com/micro/cli/v2@master

What about the `help` command? It still doesn't work properly

**Comment by asim** [comment]
It should be fixed in master

**Comment by vtolstov** [comment]
@stdatiks fixed in master now

**Comment by vtolstov** [comment]
@asim issue can be closed

**Comment by nsemikov** [comment]
@vtolstov fixed only `--help` and `-h` flags, but not `help` command

**Comment by nsemikov** [comment]
@asim reopen bug, pls - it's not finaly fixed

**Comment by vtolstov** [comment]
Before write I'm test latest cli master and greeter app, greeter help works fine and displays help message

**Comment by nsemikov** [comment]
I'm still can reproduce it

**Comment by asim** [comment]
Maybe help contribute a fix?

**Comment by vtolstov** [comment]
If you provide minimal example it can be helpful.
