### ISSUE TITLE
/etcd/clientv3 cannot use auth.callOpts (type 

### ISSUE THREAD

**Issue by shyandsy** [micro/go-micro#870]
go get -u -v github.com/micro/micro

error information 
```
# github.com/coreos/etcd/clientv3
go\src\github.com\coreos\etcd\clientv3\auth.go:121:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthEnable
go\src\github.com\coreos\etcd\clientv3\auth.go:126:74: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthDisable
go\src\github.com\coreos\etcd\clientv3\auth.go:131:152: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
go\src\github.com\coreos\etcd\clientv3\auth.go:136:144: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
go\src\github.com\coreos\etcd\clientv3\auth.go:141:86: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserDelete
go\src\github.com\coreos\etcd\clientv3\auth.go:146:122: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserChangePassword
go\src\github.com\coreos\etcd\clientv3\auth.go:151:104: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGrantRole
go\src\github.com\coreos\etcd\clientv3\auth.go:156:80: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGet
go\src\github.com\coreos\etcd\clientv3\auth.go:161:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserList
go\src\github.com\coreos\etcd\clientv3\auth.go:166:106: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserRevokeRole
```

**Comment by asim** [comment]
Please do not do go get -u

Please export go modules and do go get

```
export GO111MODULE=on
go get github.com/micro/micro
```

**Comment by shyandsy** [comment]
new error occured,

```
# github.com/lucas-clemente/quic-go/internal/handshake
C:\Users\xxxxx\go\pkg\mod\github.com\lucas-clemente\quic-go@v0.12.1\internal\handshake\crypto_setup.go:501:72: undefined: qtls.CipherSuite
C:\Users\xxxxx\go\pkg\mod\github.com\lucas-clemente\quic-go@v0.12.1\internal\handshake\crypto_setup.go:523:73: undefined: qtls.CipherSuite
```

**Comment by milosgajdos** [comment]
Please upgrade to `go 1.13` @shyandsy and try again.

**Comment by 0x2cc** [comment]
+1

**Comment by asim** [comment]
- Please `use go 1.13`
- Please `export GO111MODULE=on`
- Please `go get github.com/micro/micro` without using the -u flag

**Comment by allenkaplan** [comment]
Hi @asim,

`go get github.com/micro/micro` and `go get` still return:

`# github.com/lucas-clemente/quic-go/internal/handshake
C:\Users\allen\go\pkg\mod\github.com\lucas-clemente\quic-go@v0.12.1\internal\handshake\crypto_setup.go:501:72: undefined: qtls.CipherSuite
C:\Users\allen\go\pkg\mod\github.com\lucas-clemente\quic-go@v0.12.1\internal\handshake\crypto_setup.go:523:73: undefined: qtls.CipherSuite
`

`
GO111MODULE=on
`

**Comment by asim** [comment]
Which version of Go are you using? 

Can you also do `go clean -modcache` and ensure your go.mod and go.sum have not been modified.

**Comment by allenkaplan** [comment]
I am running go 1.13

I have cleaned, but I still receive the error. Specifically, I am receiving the error when building in a docker container with go-micro  v1.14.0.

Edit: For some reason, this only happens with 1 of 4 docker containers being built, even though they share similar (but different) go.mod files.

Perhaps this should be a new issue? 

```
C:\Users\allen\go\src\github.com\AllenKaplan\quoter\src\quote-cli>go get github.com/micro/micro
go: finding github.com/micro/micro v1.14.0
go: downloading github.com/micro/micro v1.14.0
go: extracting github.com/micro/micro v1.14.0
go: downloading github.com/micro/go-micro v1.14.0
go: downloading github.com/go-acme/lego/v3 v3.1.0
go: downloading github.com/google/uuid v1.1.1
go: extracting github.com/google/uuid v1.1.1
go: downloading github.com/xlab/treeprint v0.0.0-20181112141820-a009c3971eca
go: extracting github.com/xlab/treeprint v0.0.0-20181112141820-a009c3971eca
go: extracting github.com/micro/go-micro v1.14.0
go: extracting github.com/go-acme/lego/v3 v3.1.0
go: downloading golang.org/x/net v0.0.0-20191028085509-fe3aa8a45271
go: downloading github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: downloading github.com/forestgiant/sliceutil v0.0.0-20160425183142-94783f95db6c
go: downloading google.golang.org/grpc v1.24.0
go: downloading github.com/golang/protobuf v1.3.2
go: downloading github.com/gorilla/handlers v1.4.2
go: downloading github.com/json-iterator/go v1.1.7
go: downloading github.com/mholt/certmagic v0.7.5
go: downloading github.com/gorilla/mux v1.7.3
go: extracting github.com/gorilla/handlers v1.4.2
go: downloading github.com/miekg/dns v1.1.22
go: extracting github.com/forestgiant/sliceutil v0.0.0-20160425183142-94783f95db6c
go: extracting github.com/golang/protobuf v1.3.2
go: extracting github.com/mholt/certmagic v0.7.5
go: downloading github.com/micro/mdns v0.3.0
go: extracting github.com/json-iterator/go v1.1.7
go: extracting github.com/gorilla/mux v1.7.3
go: extracting github.com/micro/mdns v0.3.0
go: downloading github.com/olekukonko/tablewriter v0.0.1
go: downloading github.com/cloudflare/cloudflare-go v0.10.4
go: extracting github.com/miekg/dns v1.1.22
go: downloading github.com/bwmarrin/discordgo v0.19.0
go: downloading github.com/nlopes/slack v0.6.0
go: extracting google.golang.org/grpc v1.24.0
go: extracting github.com/olekukonko/tablewriter v0.0.1
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/coreos/etcd v3.3.17+incompatible
go: extracting github.com/bwmarrin/discordgo v0.19.0
go: extracting github.com/nlopes/slack v0.6.0
go: extracting golang.org/x/net v0.0.0-20191028085509-fe3aa8a45271
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: extracting github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: extracting github.com/cloudflare/cloudflare-go v0.10.4
go: extracting github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/mattn/go-runewidth v0.0.4
go: downloading golang.org/x/crypto v0.0.0-20191028145041-f83a4685e152
go: extracting github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/nats-io/nats.go v1.8.1
go: extracting github.com/mattn/go-runewidth v0.0.4
go: downloading github.com/go-log/log v0.1.0
go: extracting github.com/pkg/errors v0.8.1
go: extracting github.com/nats-io/nats.go v1.8.1
go: downloading github.com/klauspost/cpuid v1.2.0
go: downloading github.com/gorilla/websocket v1.4.1
go: extracting github.com/go-log/log v0.1.0
go: downloading github.com/mitchellh/hashstructure v1.0.0
go: downloading github.com/cenkalti/backoff/v3 v3.0.0
go: extracting golang.org/x/crypto v0.0.0-20191028145041-f83a4685e152
go: extracting github.com/mitchellh/hashstructure v1.0.0
go: extracting github.com/gorilla/websocket v1.4.1
go: extracting github.com/cenkalti/backoff/v3 v3.0.0
go: downloading golang.org/x/sys v0.0.0-20191028164358-195ce5e7f934
go: downloading golang.org/x/time v0.0.0-20190921001708-c4c64cad1fd0
go: extracting github.com/klauspost/cpuid v1.2.0
go: downloading github.com/nats-io/nkeys v0.1.0
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/lucas-clemente/quic-go v0.12.1
go: downloading github.com/micro/cli v0.2.0
go: downloading github.com/serenize/snaker v0.0.0-20171204205717-a683aaf2d516
go: extracting golang.org/x/time v0.0.0-20190921001708-c4c64cad1fd0
go: extracting github.com/coreos/etcd v3.3.17+incompatible
go: extracting github.com/micro/cli v0.2.0
go: extracting github.com/serenize/snaker v0.0.0-20171204205717-a683aaf2d516
go: downloading github.com/joncalhoun/qson v0.0.0-20170526102502-8a9cab3a62b1
go: downloading gopkg.in/telegram-bot-api.v4 v4.6.4
go: extracting github.com/lucas-clemente/quic-go v0.12.1
go: downloading google.golang.org/genproto v0.0.0-20191028173616-919d9bdd9fe6
go: extracting github.com/joncalhoun/qson v0.0.0-20170526102502-8a9cab3a62b1
go: downloading github.com/cheekybits/genny v1.0.0
go: extracting github.com/cheekybits/genny v1.0.0
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/marten-seemann/qtls v0.4.1
go: extracting github.com/nats-io/nuid v1.0.1
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: extracting github.com/marten-seemann/qtls v0.4.1
go: downloading go.uber.org/zap v1.11.0
go: extracting gopkg.in/square/go-jose.v2 v2.3.1
go: extracting go.uber.org/zap v1.11.0
go: downloading github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f
go: downloading github.com/coreos/go-systemd v0.0.0-20190719114852-fd7a80b32e1f
go: extracting google.golang.org/genproto v0.0.0-20191028173616-919d9bdd9fe6
go: extracting gopkg.in/telegram-bot-api.v4 v4.6.4
go: extracting github.com/coreos/go-systemd v0.0.0-20190719114852-fd7a80b32e1f
go: extracting github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f
go: downloading go.uber.org/multierr v1.2.0
go: downloading go.uber.org/atomic v1.4.0
go: extracting go.uber.org/multierr v1.2.0
go: downloading github.com/gogo/protobuf v1.3.1
go: extracting go.uber.org/atomic v1.4.0
go: extracting github.com/nats-io/nkeys v0.1.0
go: downloading github.com/technoweenie/multipartstreamer v1.0.1
go: extracting golang.org/x/text v0.3.2
go: extracting github.com/technoweenie/multipartstreamer v1.0.1
go: extracting github.com/gogo/protobuf v1.3.1
go: extracting golang.org/x/sys v0.0.0-20191028164358-195ce5e7f934
go: finding github.com/micro/go-micro v1.14.0
go: finding github.com/micro/cli v0.2.0
go: finding github.com/go-acme/lego/v3 v3.1.0
go: finding github.com/gorilla/mux v1.7.3
go: finding github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: finding github.com/go-log/log v0.1.0
go: finding github.com/golang/protobuf v1.3.2
go: finding github.com/google/uuid v1.1.1
go: finding github.com/cloudflare/cloudflare-go v0.10.4
go: finding github.com/bwmarrin/discordgo v0.19.0
go: finding github.com/forestgiant/sliceutil v0.0.0-20160425183142-94783f95db6c
go: finding golang.org/x/net v0.0.0-20191028085509-fe3aa8a45271
go: finding github.com/xlab/treeprint v0.0.0-20181112141820-a009c3971eca
go: finding github.com/joncalhoun/qson v0.0.0-20170526102502-8a9cab3a62b1
go: finding github.com/nlopes/slack v0.6.0
go: finding google.golang.org/grpc v1.24.0
go: finding gopkg.in/telegram-bot-api.v4 v4.6.4
go: finding github.com/nats-io/nats.go v1.8.1
go: finding github.com/micro/mdns v0.3.0
go: finding github.com/gorilla/websocket v1.4.1
go: finding github.com/miekg/dns v1.1.22
go: finding golang.org/x/crypto v0.0.0-20191028145041-f83a4685e152
go: finding github.com/technoweenie/multipartstreamer v1.0.1
go: finding github.com/olekukonko/tablewriter v0.0.1
go: finding github.com/json-iterator/go v1.1.7
go: finding github.com/serenize/snaker v0.0.0-20171204205717-a683aaf2d516
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/gorilla/handlers v1.4.2
go: finding github.com/cenkalti/backoff/v3 v3.0.0
go: finding golang.org/x/time v0.0.0-20190921001708-c4c64cad1fd0
go: finding github.com/mholt/certmagic v0.7.5
go: finding github.com/coreos/etcd v3.3.17+incompatible
go: finding golang.org/x/text v0.3.2
go: finding github.com/lucas-clemente/quic-go v0.12.1
go: finding github.com/mattn/go-runewidth v0.0.4
go: finding github.com/mitchellh/hashstructure v1.0.0
go: finding github.com/nats-io/nkeys v0.1.0
go: finding github.com/nats-io/nuid v1.0.1
go: finding golang.org/x/sys v0.0.0-20191028164358-195ce5e7f934
go: finding gopkg.in/square/go-jose.v2 v2.3.1
go: finding github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: finding github.com/modern-go/reflect2 v1.0.1
go: finding github.com/cheekybits/genny v1.0.0
go: finding google.golang.org/genproto v0.0.0-20191028173616-919d9bdd9fe6
go: finding github.com/gogo/protobuf v1.3.1
go: finding go.uber.org/zap v1.11.0
go: finding github.com/klauspost/cpuid v1.2.0
go: finding github.com/marten-seemann/qtls v0.4.1
go: finding github.com/coreos/pkg v0.0.0-20180928190104-399ea9e2e55f
go: finding go.uber.org/atomic v1.4.0
go: finding go.uber.org/multierr v1.2.0
github.com/lucas-clemente/quic-go/internal/handshake
C:\Users\allen\go\pkg\mod\github.com\lucas-clemente\quic-go@v0.12.1\internal\handshake\crypto_setup.go:501:72: undefined: qtls.CipherSuite
C:\Users\allen\go\pkg\mod\github.com\lucas-clemente\quic-go@v0.12.1\internal\handshake\crypto_setup.go:523:73: undefined: qtls.CipherSuite
```

**Comment by allenkaplan** [comment]
Fixed by the following procedure:

Deleted the `go.mod` and `go.sum` files, used `go mod init` and `go get github.com/micro/micro`

**Comment by ta2swu** [comment]
> 
> 
>     * Please `use go 1.13`
> 
>     * Please `export GO111MODULE=on`
> 
>     * Please `go get github.com/micro/micro` without using the -u flag

Hi @asim 

I tired all those steps and other approaches  yet I'm still getting errors 
---------------------------------------------------------------------
```shell
go get: github.com/micro/go-plugins@v1.4.0 requires
        k8s.io/api@v0.0.0-20190726022912-69e1bce1dad5 requires
        github.com/gogo/protobuf@v0.0.0-20190410021324-65acae22fc9: invalid pseudo-version: revision is shorter than canonical (65acae22fc9d)
```
--------------------------------------------------------------------

```shell
# github.com/coreos/etcd/clientv3
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:121:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthEnable
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:126:74: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthDisable
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:131:152: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:136:144: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:141:86: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserDelete
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:146:122: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserChangePassword
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:151:104: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGrantRole
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:156:80: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGet
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:161:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserList
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:166:106: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserRevokeRole
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:166:106: too many errors
```

**Comment by milosgajdos** [comment]
Try the following @ta2swu 
* delete modcache: `go clean -modcache`
* get all packages again `go get`

**Comment by ta2swu** [comment]
> 
> 
> Try the following @ta2swu
> 
>     * delete modcache: `go clean -modcache`
> 
>     * get all packages again `go get`

hi @milosgajdos83 

After cleaning mod and trying to get go-plugins I get the following logs

```
go get -v github.com/micro/go-plugins
go: finding github.com/micro/go-plugins v1.4.0
go: downloading github.com/micro/go-plugins v1.4.0
go: extracting github.com/micro/go-plugins v1.4.0
go get: github.com/micro/go-plugins@v1.4.0 requires
        k8s.io/api@v0.0.0-20190726022912-69e1bce1dad5 requires
        github.com/gogo/protobuf@v0.0.0-20190410021324-65acae22fc9: invalid pseudo-version: revision is shorter than canonical (65acae22fc9d)
```



on executing my program I still get the same errors

```
# github.com/coreos/etcd/clientv3
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:121:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthEnable
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:126:74: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthDisable
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:131:152: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:136:144: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:141:86: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserDelete
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:146:122: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserChangePassword
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:151:104: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGrantRole
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:156:80: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGet
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:161:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserList
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:166:106: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserRevokeRole
go\go1.13\src\github.com\coreos\etcd\clientv3\auth.go:166:106: too many errors

```

**Comment by milosgajdos** [comment]
@ta2swu can you please paste the output of `go env` to this issue?

**Comment by vtolstov** [comment]
closing as stale, also note that go-plugins/v2 does not have such error ad have separate go.mod per package. if you have problem with it, please open new issue.
